language:
    - cpp

compiler:
    - gcc

before_install:
    - wget --no-verbose --output-document=boost_1_58_0.tar.gz http://nchc.dl.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.gz
    - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost"
    - mkdir -p $BOOST_ROOT
    - tar zxf boost_1_58_0.tar.gz --strip-components=1 -C $BOOST_ROOT

install: 
    - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=system,filesystem,thread)
    - (cd $BOOST_ROOT; sudo ./b2 threading=multi link=static --prefix=/usr/local -d0 install)
script:
    - mkdir _builds
    - cd c++
    - g++ *.cpp -o ../_builds/server -pthread -lboost_system -lboost_filesystem -lboost_thread -lrt -O2 -DNDEBUG
    - cd ../_builds
    - file server
    - ldd server
    - ip addr
    - cd ..
    - ./_builds/server 0.0.0.0 9527 4 .